import { createHash } from 'node:crypto';
import { mkdir, lstat, readFile, rename, open, unlink } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { parse_studio_article, serialize_studio_article, discover_local_images } from './studio_article';
import { render_markdown_preview, studio_validation_error } from './markdown_preview';
import { cleanup_created_images, prepare_article_images, publish_prepared_images, rewrite_markdown_images, studio_image_publish_error, type cleanup_result, type cos_adapter, type image_preparation_options, type prepared_image, type published_image, type publish_result } from './studio_images';
import type { git_adapter, git_publish_result } from './studio_git';
import { studio_protocol_error, validate_studio_request, type studio_request, type studio_response, type studio_error } from './studio_protocol';

type deployment_adapter = { report(input: { public_url: string; commit_sha: string }): Promise<void> };
export type studio_publish_dependencies = { journal_root: string; image_options?: Omit<image_preparation_options, 'year' | 'slug'>; cos?: cos_adapter; git?: git_adapter; deployment?: deployment_adapter; prepare_images?: (sources: studio_request['images'], options: image_preparation_options) => Promise<prepared_image[]>; publish_images?: (images: readonly prepared_image[]) => Promise<publish_result>; cleanup_images?: (objects: readonly published_image[]) => Promise<cleanup_result> };
type journal = { protocol_version: 1; request_id: string; payload_hash: string; status: 'in_progress' | 'completed' | 'recovery_required'; target_path: string; owned: { object_key: string; version_id: string }[]; result?: studio_response };
const queues = new Map<string, Promise<void>>();
const sha256 = (value: Uint8Array | string): string => createHash('sha256').update(value).digest('hex');
const issue = (code: string, message: string, field?: string): studio_error => ({ code, message, ...(field === undefined ? {} : { field }) });
const failed = (errors: studio_error[], cleanup?: cleanup_result): studio_response => ({ protocol_version: 1, kind: 'failed', errors, ...(cleanup === undefined ? {} : { cleanup }) });
const inside = (root: string, value: string): boolean => { const item = relative(root, value); return item !== '' && !item.startsWith('..') && !isAbsolute(item); };
const payload_hash = (request: studio_request): string => sha256(JSON.stringify({ ...request, images: (request.images ?? []).map((image) => ({ ...image, bytes: sha256(image.bytes) })) }));
const journal_path = (root: string, request_id: string): string => join(root, '.studio', 'transactions', `${request_id}.json`);
const read_journal = async (path: string): Promise<journal | undefined> => { const raw = await readFile(path, 'utf8').catch((cause: unknown) => { if (typeof cause === 'object' && cause !== null && 'code' in cause && (cause as { code?: unknown }).code === 'ENOENT') return undefined; throw cause; }); if (raw === undefined) return undefined; let value: unknown; try { value = JSON.parse(raw); } catch { throw new Error('corrupt journal'); } if (typeof value !== 'object' || value === null) throw new Error('corrupt journal'); const item = value as Partial<journal>; if (item.protocol_version !== 1 || typeof item.request_id !== 'string' || !/^[a-f0-9]{64}$/.test(item.payload_hash ?? '') || !['in_progress', 'completed', 'recovery_required'].includes(item.status ?? '') || !Array.isArray(item.owned)) throw new Error('corrupt journal'); return item as journal; };
const write_journal = async (path: string, value: journal): Promise<void> => { const temporary = `${path}.${process.pid}.${Date.now()}.tmp`; let file: Awaited<ReturnType<typeof open>> | undefined; try { file = await open(temporary, 'wx', 0o600); await file.writeFile(JSON.stringify(value)); await file.sync(); await file.close(); file = undefined; await rename(temporary, path); const directory = await open(dirname(path), 'r'); await directory.sync(); await directory.close(); } finally { await file?.close().catch(() => undefined); await unlink(temporary).catch(() => undefined); } };
const validate = async (request: studio_request): Promise<ReturnType<typeof parse_studio_article>> => { await render_markdown_preview(request.markdown); const article = parse_studio_article(request.markdown, request.slug); if (article.metadata.title !== request.metadata.title || article.metadata.description !== request.metadata.description || article.metadata.date !== request.metadata.date) throw new studio_protocol_error([issue('metadata_mismatch', 'Metadata must match Markdown frontmatter.', 'metadata')]); const supplied = new Set((request.images ?? []).map((image) => image.source_path.replace(/^\.\//, ''))); const referenced = discover_local_images(request.markdown).map((item) => item.replace(/^\.\//, '')); if (referenced.some((item) => !supplied.has(item)) || [...supplied].some((item) => !referenced.includes(item))) throw new studio_protocol_error([issue('image_pairing', 'Every local Markdown image must have exactly one supplied image.', 'images')]); return article; };

/** Publishes a snapshot request and journals only hashes, identifiers, and recoverable ownership. */
export const publish_article = async (input: unknown, dependencies: studio_publish_dependencies): Promise<studio_response> => {
  let request: studio_request; try { request = validate_studio_request(input); } catch (cause) { return failed(cause instanceof studio_protocol_error ? cause.errors : [issue('invalid_request', 'Request is invalid.')]); }
  if (request.kind === 'preview') { try { await validate(request); return { protocol_version: 1, kind: 'preview', publishable: false, errors: [issue('preview_only', 'Preview requests are not publishable.')] }; } catch (cause) { return { protocol_version: 1, kind: 'preview', publishable: false, errors: cause instanceof studio_protocol_error ? cause.errors : [issue('validation', 'Preview validation failed.')] }; } }
  if (!dependencies.image_options || !dependencies.git || (!dependencies.cos && !dependencies.publish_images)) return failed([issue('not_publishable', 'Publishing is not configured locally.')]);
  const snapshot = validate_studio_request(request); if (snapshot.kind === 'preview') return failed([issue('invalid_request', 'Preview requests cannot be published.')]); const hash = payload_hash(snapshot); const queue_key = `${resolve(dependencies.journal_root)}:${snapshot.request_id}`; const previous = queues.get(queue_key) ?? Promise.resolve(); let release: (() => void) | undefined; const gate = new Promise<void>((resolve_gate) => { release = resolve_gate; }); const tail = previous.then(() => gate); queues.set(queue_key, tail); await previous;
  try {
    const root = resolve(dependencies.journal_root); const path = resolve(journal_path(root, snapshot.request_id)); if (!inside(root, path)) throw new Error('unsafe journal'); await mkdir(dirname(path), { recursive: true, mode: 0o700 }); const directory = await lstat(dirname(path)); const file = await lstat(path).catch(() => undefined); if (!directory.isDirectory() || directory.isSymbolicLink() || file?.isSymbolicLink()) throw new Error('unsafe journal');
    const old = await read_journal(path); if (old) { if (old.payload_hash !== hash) return failed([issue('request_id_conflict', 'request_id was already used for a different payload.', 'request_id')]); if (old.status === 'completed' && old.result) return old.result; return { protocol_version: 1, kind: 'recovery_required', errors: [issue('recovery_required', 'An earlier publication is incomplete; resume or cleanup its exact owned versions.')] }; }
    let article: ReturnType<typeof parse_studio_article>; try { article = await validate(snapshot); } catch (cause) { return failed(cause instanceof studio_protocol_error ? cause.errors : cause instanceof studio_validation_error ? cause.issues : [issue('validation', 'Article validation failed.')]); }
    const initial: journal = { protocol_version: 1, request_id: snapshot.request_id, payload_hash: hash, status: 'in_progress', target_path: `src/content/writing/${snapshot.slug}.md`, owned: [] }; await write_journal(path, initial); let objects: readonly published_image[] = [];
    try {
      const image_options: image_preparation_options = { ...dependencies.image_options, year: snapshot.year, slug: snapshot.slug }; const prepared = dependencies.prepare_images ? await dependencies.prepare_images(snapshot.images, image_options) : (await prepare_article_images(snapshot.images ?? [], image_options)).images; const published = dependencies.publish_images ? await dependencies.publish_images(prepared) : await publish_prepared_images(prepared, dependencies.cos!); objects = published.objects; const owned = objects.filter((item) => item.status === 'created').map((item) => ({ object_key: item.object_key, version_id: item.version_id })); await write_journal(path, { ...initial, owned });
      const urls = new Map(published.manifest.map((item) => [item.source_path, item.public_url])); const source = new TextEncoder().encode(serialize_studio_article({ ...article, body: rewrite_markdown_images(article.body, urls), metadata: { ...article.metadata, assets: published.manifest } })); const git_result: git_publish_result = await dependencies.git.publish({ operation: snapshot.kind, slug: snapshot.slug, source, commit_message: snapshot.commit_message, ...(snapshot.kind === 'publish_update' ? { expected_source_hash: snapshot.expected_source_hash } : {}) });
      if (!git_result.ok && git_result.code === 'push_failed') { const result: studio_response = { protocol_version: 1, kind: 'committed_local', commit_sha: git_result.commit_sha, recovery: git_result.recovery }; await write_journal(path, { ...initial, owned, status: 'completed', result }); return result; }
      if (!git_result.ok) { const cleanup = dependencies.cleanup_images ? await dependencies.cleanup_images(objects) : await cleanup_created_images(objects, dependencies.cos!); const result = failed([issue(git_result.code, git_result.message)], cleanup); await write_journal(path, { ...initial, owned, status: cleanup.failures.length ? 'recovery_required' : 'completed', result }); return result; }
      const public_url = `${new URL(dependencies.image_options.public_base_url).origin}/articles/${snapshot.slug}/`; let deployment_advisory: string | undefined; try { await dependencies.deployment?.report({ public_url, commit_sha: git_result.commit_sha }); } catch { deployment_advisory = 'Deployment status could not be confirmed.'; } const result: studio_response = { protocol_version: 1, kind: 'published', public_url, commit_sha: git_result.commit_sha, ...(deployment_advisory === undefined ? {} : { deployment_advisory }) }; await write_journal(path, { ...initial, owned, status: 'completed', result }); return result;
    } catch (cause) { if (cause instanceof studio_image_publish_error) objects = cause.successful_objects; const cleanup = dependencies.cleanup_images ? await dependencies.cleanup_images(objects) : await cleanup_created_images(objects, dependencies.cos!); const result = failed([issue('publication_failed', cause instanceof Error ? cause.message.replace(/[\r\n].*/s, '') : 'Publication failed.')], cleanup); const owned = objects.filter((item) => item.status === 'created').map((item) => ({ object_key: item.object_key, version_id: item.version_id })); await write_journal(path, { ...initial, owned, status: cleanup.failures.length ? 'recovery_required' : 'completed', result }); return result; }
  } catch { return failed([issue('journal_failure', 'Publication journal is unavailable.')]); } finally { release?.(); if (queues.get(queue_key) === tail) queues.delete(queue_key); }
};
