/** JSON-safe protocol for the local Markdown Studio. Image bytes are bounded base64. */
export const studio_protocol_version = 1 as const;
export type studio_error = { code: string; field?: string; message: string };
export type studio_image_input = { source_path: string; bytes_base64: string; claimed_content_type: 'image/jpeg' | 'image/png'; intent: 'photo' | 'screenshot' | 'diagram'; semantic_name: string };
export type normalized_studio_image = Omit<studio_image_input, 'bytes_base64'> & { bytes: Uint8Array };
export type studio_asset_input = { source_path: string; object_key: string; public_url: string };
export type studio_metadata_input = { title: string; description: string; date: string; updated?: string; tags?: string[]; language?: 'zh' | 'en'; translation?: string; featured?: boolean; draft?: boolean; assets?: studio_asset_input[]; social?: { zhihu: boolean; wechat: boolean; xiaohongshu: boolean } };
type base = { protocol_version: 1; request_id: string; slug: string; year: number; markdown: string; metadata: studio_metadata_input; images?: normalized_studio_image[] };
export type studio_preview_request = base & { kind: 'preview' }; export type studio_publish_new_request = base & { kind: 'publish_new'; commit_message: string }; export type studio_publish_update_request = base & { kind: 'publish_update'; commit_message: string; expected_source_hash: string }; export type studio_request = studio_preview_request | studio_publish_new_request | studio_publish_update_request;
export type studio_response = { protocol_version: 1; kind: 'preview'; publishable: boolean; errors: studio_error[] } | { protocol_version: 1; kind: 'published'; public_url: string; commit_sha: string; deployment_advisory?: string } | { protocol_version: 1; kind: 'committed_local'; commit_sha: string; recovery: string } | { protocol_version: 1; kind: 'failed'; errors: studio_error[]; cleanup?: { deleted: string[]; failures: string[] } } | { protocol_version: 1; kind: 'recovery_required'; errors: studio_error[] } | { protocol_version: 1; kind: 'recovered_stale_claim'; errors: [] };
export class studio_protocol_error extends Error { constructor(readonly errors: studio_error[]) { super(errors.map((item) => item.message).join('; ')); } }
const request_id_pattern = /^(?:[a-f0-9]{32}|[a-f0-9]{64}|[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12})$/; const slug_pattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const is_record = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const text = (value: unknown, field: string, errors: studio_error[], max = 200_000): string | undefined => { if (typeof value !== 'string' || !value || value.length > max) { errors.push({ code: 'invalid_field', field, message: `${field} must be a bounded non-empty string.` }); return undefined; } return value; };
const unknowns = (value: Record<string, unknown>, allowed: readonly string[], errors: studio_error[]): void => { for (const key of Object.keys(value)) if (!allowed.includes(key)) errors.push({ code: 'invalid_field', field: key, message: `Unknown field: ${key}.` }); };
const date = (value: unknown, field: string, errors: studio_error[]): string | undefined => { const result = text(value, field, errors, 10); if (result && !/^\d{4}-\d{2}-\d{2}$/.test(result)) errors.push({ code: 'invalid_metadata', field, message: `${field} must be YYYY-MM-DD.` }); return result; };
const decode = (value: string): Uint8Array | undefined => { if (!/^[A-Za-z0-9+/]*={0,2}$/.test(value) || value.length % 4 !== 0) return undefined; const bytes = Buffer.from(value, 'base64'); return Buffer.from(bytes).toString('base64') === value ? new Uint8Array(bytes) : undefined; };

/** Returns whether a JSON-safe value is one complete Studio error item. */
const is_studio_error = (value: unknown): value is studio_error => is_record(value) && Object.keys(value).every((key) => ['code', 'field', 'message'].includes(key)) && typeof value.code === 'string' && value.code.length > 0 && value.code.length <= 200 && typeof value.message === 'string' && value.message.length > 0 && value.message.length <= 2_000 && (value.field === undefined || (typeof value.field === 'string' && value.field.length > 0 && value.field.length <= 200));

/** Returns whether a value is an exact cleanup report safe to replay from a journal. */
const is_cleanup = (value: unknown): value is { deleted: string[]; failures: string[] } => is_record(value) && Object.keys(value).every((key) => ['deleted', 'failures'].includes(key)) && Array.isArray(value.deleted) && Array.isArray(value.failures) && value.deleted.every((item) => typeof item === 'string' && item.length > 0) && value.failures.every((item) => typeof item === 'string' && item.length > 0);

/** Validates every persisted response variant before a transaction journal can replay it. */
export const is_studio_response = (value: unknown): value is studio_response => {
  if (!is_record(value) || value.protocol_version !== 1 || typeof value.kind !== 'string') return false;
  const has_only = (keys: readonly string[]): boolean => Object.keys(value).every((key) => keys.includes(key));
  if (value.kind === 'preview') return has_only(['protocol_version', 'kind', 'publishable', 'errors']) && typeof value.publishable === 'boolean' && Array.isArray(value.errors) && value.errors.every(is_studio_error);
  if (value.kind === 'published') return has_only(['protocol_version', 'kind', 'public_url', 'commit_sha', 'deployment_advisory']) && typeof value.public_url === 'string' && /^https:\/\//.test(value.public_url) && typeof value.commit_sha === 'string' && /^[a-f0-9]{40}$/.test(value.commit_sha) && (value.deployment_advisory === undefined || (typeof value.deployment_advisory === 'string' && value.deployment_advisory.length > 0));
  if (value.kind === 'committed_local') return has_only(['protocol_version', 'kind', 'commit_sha', 'recovery']) && typeof value.commit_sha === 'string' && /^[a-f0-9]{40}$/.test(value.commit_sha) && typeof value.recovery === 'string' && value.recovery.length > 0;
  if (value.kind === 'failed') return has_only(['protocol_version', 'kind', 'errors', 'cleanup']) && Array.isArray(value.errors) && value.errors.every(is_studio_error) && (value.cleanup === undefined || is_cleanup(value.cleanup));
  if (value.kind === 'recovery_required') return has_only(['protocol_version', 'kind', 'errors']) && Array.isArray(value.errors) && value.errors.every(is_studio_error);
  return value.kind === 'recovered_stale_claim' && has_only(['protocol_version', 'kind', 'errors']) && Array.isArray(value.errors) && value.errors.length === 0;
};

/** Validates JSON input, rejecting unsupported fields and snapshotting decoded image bytes. */
export const validate_studio_request = (value: unknown): studio_request => {
  const errors: studio_error[] = []; if (!is_record(value)) throw new studio_protocol_error([{ code: 'invalid_request', message: 'Request must be an object.' }]); const kind = value.kind;
  const common = ['protocol_version', 'kind', 'request_id', 'slug', 'year', 'markdown', 'metadata', 'images']; unknowns(value, kind === 'publish_update' ? [...common, 'commit_message', 'expected_source_hash'] : kind === 'publish_new' ? [...common, 'commit_message'] : common, errors);
  if (kind !== 'preview' && kind !== 'publish_new' && kind !== 'publish_update') errors.push({ code: 'invalid_kind', field: 'kind', message: 'Invalid request kind.' }); if (value.protocol_version !== 1) errors.push({ code: 'invalid_version', field: 'protocol_version', message: 'protocol_version must be 1.' });
  const request_id = text(value.request_id, 'request_id', errors, 64); if (request_id && !request_id_pattern.test(request_id)) errors.push({ code: 'invalid_request_id', field: 'request_id', message: 'request_id must be lowercase UUID or 32/64 hex.' }); const slug = text(value.slug, 'slug', errors, 100); if (slug && !slug_pattern.test(slug)) errors.push({ code: 'invalid_slug', field: 'slug', message: 'Invalid slug.' }); const markdown = text(value.markdown, 'markdown', errors, 1_000_000); if (!Number.isInteger(value.year) || (value.year as number) < 2000 || (value.year as number) > 9999) errors.push({ code: 'invalid_year', field: 'year', message: 'Invalid year.' });
  const raw_metadata = is_record(value.metadata) ? value.metadata : {}; if (!is_record(value.metadata)) errors.push({ code: 'invalid_metadata', field: 'metadata', message: 'metadata must be an object.' }); unknowns(raw_metadata, ['title', 'description', 'date', 'updated', 'tags', 'language', 'translation', 'featured', 'draft', 'assets', 'social'], errors); const title = text(raw_metadata.title, 'metadata.title', errors, 300); const description = text(raw_metadata.description, 'metadata.description', errors, 1000); const published_date = date(raw_metadata.date, 'metadata.date', errors); const updated = raw_metadata.updated === undefined ? undefined : date(raw_metadata.updated, 'metadata.updated', errors); const tags = raw_metadata.tags === undefined ? undefined : Array.isArray(raw_metadata.tags) && raw_metadata.tags.every((item) => typeof item === 'string' && item.length > 0 && item.length <= 80) ? [...raw_metadata.tags] as string[] : (() => { errors.push({ code: 'invalid_metadata', field: 'metadata.tags', message: 'Invalid tags.' }); return undefined; })();
  if (raw_metadata.language !== undefined && raw_metadata.language !== 'zh' && raw_metadata.language !== 'en') errors.push({ code: 'invalid_metadata', field: 'metadata.language', message: 'Invalid language.' }); const translation = raw_metadata.translation === undefined ? undefined : text(raw_metadata.translation, 'metadata.translation', errors, 200); if (raw_metadata.featured !== undefined && typeof raw_metadata.featured !== 'boolean') errors.push({ code: 'invalid_metadata', field: 'metadata.featured', message: 'featured must be boolean.' }); if (raw_metadata.draft !== undefined && typeof raw_metadata.draft !== 'boolean') errors.push({ code: 'invalid_metadata', field: 'metadata.draft', message: 'draft must be boolean.' }); const social = raw_metadata.social === undefined ? undefined : is_record(raw_metadata.social) && typeof raw_metadata.social.zhihu === 'boolean' && typeof raw_metadata.social.wechat === 'boolean' && typeof raw_metadata.social.xiaohongshu === 'boolean' ? { zhihu: raw_metadata.social.zhihu, wechat: raw_metadata.social.wechat, xiaohongshu: raw_metadata.social.xiaohongshu } : (errors.push({ code: 'invalid_metadata', field: 'metadata.social', message: 'social requires all boolean channels.' }), undefined);
  const images: normalized_studio_image[] = []; const raw_images = value.images ?? []; if (!Array.isArray(raw_images) || raw_images.length > 20) errors.push({ code: 'invalid_images', field: 'images', message: 'images must contain at most 20 items.' }); if (Array.isArray(raw_images)) for (const [index, raw] of raw_images.entries()) { if (!is_record(raw)) { errors.push({ code: 'invalid_image', field: `images[${index}]`, message: 'Image must be an object.' }); continue; } unknowns(raw, ['source_path', 'bytes_base64', 'claimed_content_type', 'intent', 'semantic_name'], errors); const bytes_base64 = text(raw.bytes_base64, `images[${index}].bytes_base64`, errors, 26_666_668); const bytes = bytes_base64 ? decode(bytes_base64) : undefined; if (!bytes || !bytes.byteLength || bytes.byteLength > 20_000_000 || typeof raw.source_path !== 'string' || typeof raw.semantic_name !== 'string' || (raw.claimed_content_type !== 'image/jpeg' && raw.claimed_content_type !== 'image/png') || (raw.intent !== 'photo' && raw.intent !== 'screenshot' && raw.intent !== 'diagram')) { errors.push({ code: 'invalid_image', field: `images[${index}]`, message: 'Invalid image.' }); continue; } images.push({ source_path: raw.source_path, bytes: new Uint8Array(bytes), claimed_content_type: raw.claimed_content_type, intent: raw.intent, semantic_name: raw.semantic_name }); }
  const commit_message = kind === 'publish_new' || kind === 'publish_update' ? text(value.commit_message, 'commit_message', errors, 200) : undefined; const expected_source_hash = kind === 'publish_update' ? text(value.expected_source_hash, 'expected_source_hash', errors, 64) : undefined; if (expected_source_hash && !/^[a-f0-9]{64}$/.test(expected_source_hash)) errors.push({ code: 'invalid_hash', field: 'expected_source_hash', message: 'Invalid SHA-256.' });
  const assets = raw_metadata.assets === undefined ? undefined : Array.isArray(raw_metadata.assets) && raw_metadata.assets.every((asset) => is_record(asset) && Object.keys(asset).every((key) => ['source_path', 'object_key', 'public_url'].includes(key)) && typeof asset.source_path === 'string' && asset.source_path.length > 0 && asset.source_path.length <= 500 && typeof asset.object_key === 'string' && asset.object_key.length > 0 && asset.object_key.length <= 1_000 && typeof asset.public_url === 'string' && /^https:\/\//.test(asset.public_url) && asset.public_url.length <= 2_000) ? raw_metadata.assets.map((asset) => ({ source_path: asset.source_path as string, object_key: asset.object_key as string, public_url: asset.public_url as string })) : (errors.push({ code: 'invalid_metadata', field: 'metadata.assets', message: 'Invalid asset manifest.' }), undefined);
  if (errors.length || !request_id || !slug || markdown === undefined || !title || !description || !published_date || (kind !== 'preview' && !commit_message) || (kind === 'publish_update' && !expected_source_hash)) throw new studio_protocol_error(errors);
  const metadata: studio_metadata_input = { title, description, date: published_date, ...(updated ? { updated } : {}), ...(tags ? { tags } : {}), ...(raw_metadata.language === 'zh' || raw_metadata.language === 'en' ? { language: raw_metadata.language } : {}), ...(translation ? { translation } : {}), ...(typeof raw_metadata.featured === 'boolean' ? { featured: raw_metadata.featured } : {}), ...(typeof raw_metadata.draft === 'boolean' ? { draft: raw_metadata.draft } : {}), ...(assets ? { assets } : {}), ...(social ? { social } : {}) }; const base_value: base = { protocol_version: 1, request_id, slug, year: value.year as number, markdown, metadata, ...(images.length ? { images } : {}) };
  if (kind === 'preview') return { ...base_value, kind }; if (kind === 'publish_new') return { ...base_value, kind, commit_message: commit_message! }; if (kind === 'publish_update') return { ...base_value, kind, commit_message: commit_message!, expected_source_hash: expected_source_hash! }; throw new studio_protocol_error(errors);
};
