import { createHash } from 'node:crypto';
import { mkdir, lstat, readFile, rename, open, unlink } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { parse_studio_article, serialize_studio_article, discover_local_images } from './studio_article';
import { render_markdown_preview, studio_validation_error } from './markdown_preview';
import { cleanup_created_images, prepare_article_images, publish_prepared_images, rewrite_markdown_images, studio_image_publish_error, type cleanup_result, type cos_adapter, type image_preparation_options, type prepared_image, type published_image, type publish_result } from './studio_images';
import type { git_adapter, git_publish_result } from './studio_git';
import { studio_protocol_error, validate_studio_request, type studio_request, type studio_response, type studio_error } from './studio_protocol';

type deployment_adapter = { report(input: { public_url: string; commit_sha: string }): Promise<void> };
export type studio_publish_dependencies = { journal_root: string; public_site_url?: string; image_options?: Omit<image_preparation_options, 'year' | 'slug'>; cos?: cos_adapter; git?: git_adapter; deployment?: deployment_adapter; prepare_images?: (sources: studio_request['images'], options: image_preparation_options) => Promise<prepared_image[]>; publish_images?: (images: readonly prepared_image[]) => Promise<publish_result>; cleanup_images?: (objects: readonly published_image[]) => Promise<cleanup_result> };
type transaction_phase = 'pre_commit' | 'committed' | 'pushed';
type journal = { protocol_version: 1; request_id: string; payload_hash: string; status: 'in_progress' | 'completed' | 'recovery_required'; phase: transaction_phase; target_path: string; owned: { object_key: string; version_id: string }[]; commit_sha?: string; result?: studio_response };
const queues = new Map<string, Promise<void>>();
const sha256 = (value: Uint8Array | string): string => createHash('sha256').update(value).digest('hex');
const issue = (code: string, message: string, field?: string): studio_error => ({ code, message, ...(field === undefined ? {} : { field }) });
const failed = (errors: studio_error[], cleanup?: cleanup_result): studio_response => ({ protocol_version: 1, kind: 'failed', errors, ...(cleanup === undefined ? {} : { cleanup }) });
const inside = (root: string, value: string): boolean => { const item = relative(root, value); return item !== '' && !item.startsWith('..') && !isAbsolute(item); };
const payload_hash = (request: studio_request): string => sha256(JSON.stringify({ ...request, images: (request.images ?? []).map((image) => ({ ...image, bytes: sha256(image.bytes) })) }));
const journal_path = (root: string, request_id: string): string => join(root, '.studio', 'transactions', `${request_id}.json`);
const valid_result = (value: unknown): value is studio_response => typeof value === 'object' && value !== null && (value as { protocol_version?: unknown }).protocol_version === 1 && typeof (value as { kind?: unknown }).kind === 'string';
const read_journal = async (path: string): Promise<journal | undefined> => { const raw = await readFile(path, 'utf8').catch((cause: unknown) => { if (typeof cause === 'object' && cause !== null && 'code' in cause && (cause as { code?: unknown }).code === 'ENOENT') return undefined; throw cause; }); if (raw === undefined) return undefined; let value: unknown; try { value = JSON.parse(raw); } catch { throw new Error('corrupt journal'); } if (typeof value !== 'object' || value === null) throw new Error('corrupt journal'); const item = value as Partial<journal>; if (item.protocol_version !== 1 || typeof item.request_id !== 'string' || !/^(?:[a-f0-9]{32}|[a-f0-9]{64}|[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12})$/.test(item.request_id) || !/^[a-f0-9]{64}$/.test(item.payload_hash ?? '') || !['in_progress', 'completed', 'recovery_required'].includes(item.status ?? '') || !['pre_commit', 'committed', 'pushed'].includes(item.phase ?? '') || typeof item.target_path !== 'string' || !Array.isArray(item.owned) || !item.owned.every((owned) => typeof owned === 'object' && owned !== null && typeof (owned as { object_key?: unknown }).object_key === 'string' && typeof (owned as { version_id?: unknown }).version_id === 'string' && (owned as { version_id: string }).version_id.length > 0) || (item.status === 'completed' && !valid_result(item.result)) || (item.commit_sha !== undefined && !/^[a-f0-9]{40}$/.test(item.commit_sha))) throw new Error('corrupt journal'); return item as journal; };
const write_journal = async (path: string, value: journal): Promise<void> => { const temporary = `${path}.${process.pid}.${Date.now()}.tmp`; let file: Awaited<ReturnType<typeof open>> | undefined; try { file = await open(temporary, 'wx', 0o600); await file.writeFile(JSON.stringify(value)); await file.sync(); await file.close(); file = undefined; await rename(temporary, path); const directory = await open(dirname(path), 'r'); await directory.sync(); await directory.close(); } finally { await file?.close().catch(() => undefined); await unlink(temporary).catch(() => undefined); } };
const validate = async (request: studio_request): Promise<ReturnType<typeof parse_studio_article>> => { await render_markdown_preview(request.markdown); const article = parse_studio_article(request.markdown, request.slug); const supplied = new Set((request.images ?? []).map((image) => image.source_path.replace(/^\.\//, ''))); const referenced = discover_local_images(request.markdown).map((item) => item.replace(/^\.\//, '')); if (referenced.some((item) => !supplied.has(item)) || [...supplied].some((item) => !referenced.includes(item))) throw new studio_protocol_error([issue('image_pairing', 'Every local Markdown image must have exactly one supplied image.', 'images')]); return article; };

/** Reconciles an interrupted request by deleting only journal-owned exact object versions. */
export const cleanup_studio_transaction = async (journal_root: string, request_id: string, adapter: cos_adapter): Promise<studio_response> => {
  try { const root = resolve(journal_root); const path = resolve(journal_path(root, request_id)); if (!inside(root, path)) return { protocol_version: 1, kind: 'recovery_required', errors: [issue('unsafe_journal', 'Journal path is unsafe.')] }; const journal = await read_journal(path); if (!journal) return { protocol_version: 1, kind: 'recovery_required', errors: [issue('missing_journal', 'No transaction journal exists.')] }; if (journal.phase !== 'pre_commit') return { protocol_version: 1, kind: 'recovery_required', errors: [issue('commit_retained', 'Committed transactions retain their images and cannot be cleaned up.')] }; if (journal.status === 'completed' && journal.result) return journal.result; const lock = await open(`${path}.lock`, 'wx', 0o600).catch(() => undefined); if (!lock) return { protocol_version: 1, kind: 'recovery_required', errors: [issue('request_claimed', 'Transaction is actively claimed.')] }; try { const deleted: string[] = []; const failures: string[] = []; for (const owned of journal.owned) try { await adapter.delete_object(owned.object_key, owned.version_id); deleted.push(owned.object_key); } catch { failures.push(owned.object_key); } const result = failed([issue('reconciled', failures.length ? 'Some exact versions could not be removed.' : 'Owned versions were removed.')], { deleted, failures }); await write_journal(path, { ...journal, status: failures.length ? 'recovery_required' : 'completed', result }); return result; } finally { await lock.close(); await unlink(`${path}.lock`).catch(() => undefined); } } catch { return { protocol_version: 1, kind: 'recovery_required', errors: [issue('corrupt_journal', 'Journal is corrupt or unavailable; no objects were deleted.')] }; }
};

/** Publishes a snapshot request and journals only hashes, identifiers, and recoverable ownership. */
export const publish_article = async (input: unknown, dependencies: studio_publish_dependencies): Promise<studio_response> => {
  let request: studio_request; try { request = validate_studio_request(input); } catch (cause) { return failed(cause instanceof studio_protocol_error ? cause.errors : [issue('invalid_request', 'Request is invalid.')]); }
  if (request.kind === 'preview') { try { await validate(request); return { protocol_version: 1, kind: 'preview', publishable: false, errors: [issue('preview_only', 'Preview requests are not publishable.')] }; } catch (cause) { return { protocol_version: 1, kind: 'preview', publishable: false, errors: cause instanceof studio_protocol_error ? cause.errors : [issue('validation', 'Preview validation failed.')] }; } }
  if (!dependencies.image_options || !dependencies.git || !dependencies.public_site_url || (!dependencies.cos && !dependencies.publish_images)) return failed([issue('not_publishable', 'Publishing is not configured locally.')]);
  const snapshot: studio_request = { ...request, metadata: { ...request.metadata, ...(request.metadata.tags ? { tags: [...request.metadata.tags] } : {}), ...(request.metadata.social ? { social: { ...request.metadata.social } } : {}) }, ...(request.images ? { images: request.images.map((image) => ({ ...image, bytes: new Uint8Array(image.bytes) })) } : {}) }; const hash = payload_hash(snapshot); const queue_key = `${resolve(dependencies.journal_root)}:${snapshot.request_id}`; const previous = queues.get(queue_key) ?? Promise.resolve(); let release: (() => void) | undefined; const gate = new Promise<void>((resolve_gate) => { release = resolve_gate; }); const tail = previous.then(() => gate); queues.set(queue_key, tail); await previous;
  let claim_path: string | undefined; let claim_token: string | undefined;
  try {
    const root = resolve(dependencies.journal_root); const path = resolve(journal_path(root, snapshot.request_id)); if (!inside(root, path)) throw new Error('unsafe journal'); await mkdir(dirname(path), { recursive: true, mode: 0o700 }); const directory = await lstat(dirname(path)); const file = await lstat(path).catch(() => undefined); if (!directory.isDirectory() || directory.isSymbolicLink() || file?.isSymbolicLink()) throw new Error('unsafe journal'); claim_path = `${path}.lock`; claim_token = sha256(`${process.pid}:${Date.now()}:${Math.random()}`); const claim = await open(claim_path, 'wx', 0o600).catch(() => undefined); if (!claim) { const existing = await read_journal(path).catch(() => undefined); if (existing?.payload_hash && existing.payload_hash !== hash) return failed([issue('request_id_conflict', 'request_id is claimed for another payload.', 'request_id')]); if (existing?.status === 'completed' && existing.result) return existing.result; return { protocol_version: 1, kind: 'recovery_required', errors: [issue('request_claimed', 'Another process owns this request or a crashed claim needs explicit reconciliation.')] }; } await claim.writeFile(JSON.stringify({ token: claim_token, pid: process.pid, created_at: new Date().toISOString(), payload_hash: hash })); await claim.sync(); await claim.close();
    const old = await read_journal(path); if (old) { if (old.payload_hash !== hash) return failed([issue('request_id_conflict', 'request_id was already used for a different payload.', 'request_id')]); if (old.status === 'completed' && old.result) return old.result; return { protocol_version: 1, kind: 'recovery_required', errors: [issue('recovery_required', 'An earlier publication is incomplete; resume or cleanup its exact owned versions.')] }; }
    let article: ReturnType<typeof parse_studio_article>; try { article = await validate(snapshot); } catch (cause) { return failed(cause instanceof studio_protocol_error ? cause.errors : cause instanceof studio_validation_error ? cause.issues : [issue('validation', 'Article validation failed.')]); }
    const initial: journal = { protocol_version: 1, request_id: snapshot.request_id, payload_hash: hash, status: 'in_progress', phase: 'pre_commit', target_path: `src/content/writing/${snapshot.slug}.md`, owned: [] }; await write_journal(path, initial); let objects: readonly published_image[] = []; let committed_sha: string | undefined;
    try {
      const image_options: image_preparation_options = { ...dependencies.image_options, year: snapshot.year, slug: snapshot.slug }; const prepared = dependencies.prepare_images ? await dependencies.prepare_images(snapshot.images, image_options) : (await prepare_article_images(snapshot.images ?? [], image_options)).images; const created: Extract<published_image, { status: 'created' }>[] = []; const published = dependencies.publish_images ? await dependencies.publish_images(prepared) : await publish_prepared_images(prepared, dependencies.cos!, async (image) => { if (image.status === 'created') { created.push(image); await write_journal(path, { ...initial, owned: created.map((item) => ({ object_key: item.object_key, version_id: item.version_id })) }); } }); objects = published.objects; const owned = objects.filter((item): item is Extract<published_image, { status: 'created' }> => item.status === 'created').map((item) => ({ object_key: item.object_key, version_id: item.version_id })); await write_journal(path, { ...initial, owned });
      const urls = new Map(published.manifest.map((item) => [item.source_path, item.public_url])); const source = new TextEncoder().encode(serialize_studio_article({ ...article, body: rewrite_markdown_images(article.body, urls), metadata: { ...article.metadata, ...snapshot.metadata, slug: snapshot.slug, assets: published.manifest } })); const git_result: git_publish_result = await dependencies.git.publish({ operation: snapshot.kind, slug: snapshot.slug, source, commit_message: snapshot.commit_message, ...(snapshot.kind === 'publish_update' ? { expected_source_hash: snapshot.expected_source_hash } : {}) });
      if (!git_result.ok && git_result.commit_retained === true && 'commit_sha' in git_result) { committed_sha = git_result.commit_sha; const result: studio_response = { protocol_version: 1, kind: 'committed_local', commit_sha: git_result.commit_sha, recovery: git_result.code === 'push_failed' ? git_result.recovery : 'Local commit is retained; inspect Git state before retrying.' }; await write_journal(path, { ...initial, owned, phase: 'committed', commit_sha: committed_sha, status: 'completed', result }); return result; }
      if (!git_result.ok) { const cleanup = dependencies.cleanup_images ? await dependencies.cleanup_images(objects) : await cleanup_created_images(objects, dependencies.cos!); const result = failed([issue(git_result.code, git_result.message)], cleanup); await write_journal(path, { ...initial, owned, status: cleanup.failures.length ? 'recovery_required' : 'completed', result }); return result; }
      committed_sha = git_result.commit_sha; await write_journal(path, { ...initial, owned, phase: 'committed', commit_sha: committed_sha }); const public_url = new URL(`/articles/${snapshot.slug}/`, dependencies.public_site_url).toString(); let deployment_advisory: string | undefined; try { await dependencies.deployment?.report({ public_url, commit_sha: git_result.commit_sha }); } catch { deployment_advisory = 'Deployment status could not be confirmed.'; } const result: studio_response = { protocol_version: 1, kind: 'published', public_url, commit_sha: git_result.commit_sha, ...(deployment_advisory === undefined ? {} : { deployment_advisory }) }; await write_journal(path, { ...initial, owned, phase: 'pushed', commit_sha: committed_sha, status: 'completed', result }); return result;
    } catch (cause) { if (committed_sha) return { protocol_version: 1, kind: 'committed_local', commit_sha: committed_sha, recovery: 'Local commit is retained. Inspect the transaction journal and push or reconcile manually.' }; if (cause instanceof studio_image_publish_error) objects = cause.successful_objects; const cleanup = dependencies.cleanup_images ? await dependencies.cleanup_images(objects) : await cleanup_created_images(objects, dependencies.cos!); const result = failed([issue('publication_failed', cause instanceof Error ? cause.message.replace(/[\r\n].*/s, '') : 'Publication failed.')], cleanup); const owned = objects.filter((item) => item.status === 'created').map((item) => ({ object_key: item.object_key, version_id: item.version_id })); await write_journal(path, { ...initial, owned, status: cleanup.failures.length ? 'recovery_required' : 'completed', result }); return result; }
  } catch { return failed([issue('journal_failure', 'Publication journal is unavailable.')]); } finally { if (claim_path && claim_token) { const owner = await readFile(claim_path, 'utf8').catch(() => ''); try { if ((JSON.parse(owner) as { token?: unknown }).token === claim_token) await unlink(claim_path); } catch { /* never remove an unreadable or foreign claim */ } } release?.(); if (queues.get(queue_key) === tail) queues.delete(queue_key); }
};
