services:
  jekyll-text-theme_dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    container_name: jekyll-TeXt-theme_default
    volumes:
      - ..:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t