services:
  jekyll:
    image: ruby:3.1
    working_dir: /usr/src/app
    volumes:
      - ..:/usr/src/app
    ports:
      - 4000:4000
    command: bash -c "bundle install && bundle exec jekyll serve -H 0.0.0.0 -t --force_polling"